### ISSUE TITLE
Filelists of Splits

### ISSUE THREAD

**Issue by leonardoboulitreau** [audeering/w2v2-age-gender-how-to#8]
Hello! 

First, congrats for the nice work!

I'd like to know if you plan to release the lists of the files used in training, val, and test, for each of the datasets considered, as mentioned in the paper!

Cheers!

**Comment by hagenw** [comment]
The splits are also provided at https://zenodo.org/doi/10.5281/zenodo.7761386.
We should maybe update the README, to highlight this more.

**Comment by leonardoboulitreau** [comment]
Oh... Thank you very much!
